pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                url: 'https://github.com/Safiquddin/automation.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    cd python-jenkins-argocd-k8s && docker build -t safiquddin/python-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    cd python-jenkins-argocd-k8s && docker push safiquddin/python-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
    
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cd python-jenkins-argocd-k8s/deploy
                        cat deploy.yaml
                        sed -i '' "s/v1/${BUILD_NUMBER}/g" deploy.yaml
                        sed -i '' "s/v1/${BUILD_NUMBER}/g" pod.yaml
                        cat deploy.yaml
                        cat pod.yaml
                        git add deploy.yaml pod.yaml
                        git commit -m 'Updated the deploy & pod yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/Safiquddin/automation.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
